[package]
name = "lumino-midi-io"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
libloading = "0.9.0"
midir = "0.10.3"
thiserror = { workspace = true }
tracing = { workspace = true }
xsynth-core = "0.3"
xsynth-soundfonts = "0.3"
lumino-realtime = { workspace = true }
cpal = "0.15"
crossbeam-channel = "0.5"
spin_sleep = "1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Media_Audio"] }
