[package]
name = "lumino-memtrace"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
tracing = { workspace = true }

[target.'cfg(not(target_os = "macos"))'.dependencies]
mimalloc = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
tikv-jemallocator = { workspace = true }
tikv-jemalloc-ctl = { workspace = true }
