[package]
name = "lumino-cache"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
lumino-midi = { path = "../midi" }
midly = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
memmap2 = "0.9"

[dev-dependencies]
tokio = { version = "1.42", features = ["rt", "macros", "fs"] }
chrono = "0.4"

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["psapi", "processthreadsapi"] }
