[package]
name = "lumino-realtime"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["xsynth-realtime"]
xsynth-realtime = ["dep:xsynth-realtime", "xsynth-core", "xsynth-soundfonts"]

[dependencies]
xsynth-core = { workspace = true, optional = true }
xsynth-soundfonts = { workspace = true, optional = true }
xsynth-realtime = { workspace = true, optional = true }
tracing = { workspace = true }
