[package]
name = "lumino-dialog"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
lumino-core = { workspace = true }
lumino-gfx = { workspace = true }
lumino-ui = { workspace = true }
# crates.io
winit = { workspace = true }
tracing = { workspace = true }
puffin = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { workspace = true }
raw-window-handle = { workspace = true }
