[package]
name = "lumino-midi"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
libloading = "0.9.0"
midir = "0.10.3"
thiserror = { workspace = true }
tracing = { workspace = true }
xsynth-core = { git = "https://github.com/buickmeow/xsynth", rev = "33ff82a4d1904a772330a8edf7b426aab4221e54" }
xsynth-realtime = { git = "https://github.com/buickmeow/xsynth", rev = "33ff82a4d1904a772330a8edf7b426aab4221e54" }
xsynth-soundfonts = { git = "https://github.com/buickmeow/xsynth", rev = "33ff82a4d1904a772330a8edf7b426aab4221e54" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Media_Audio"] }
