[package]
name = "lumino-onion-skin-hires"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
lumino-onion-skin = { workspace = true }
lumino-memory-monitor = { workspace = true }
rayon = "1.10"
xxhash-rust = { workspace = true }
wgpu = "27.0"
bytemuck = { version = "1.21", features = ["derive"] }
zstd = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
