[package]
name = "lumino-editor-state"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
description.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
lumino-core = { workspace = true }
lumino-note-core = { workspace = true }
lumino-midi-model = { workspace = true }
im = { version = "15.1.0", features = ["rayon"] }
bit-vec = "0.8"