[package]
name = "lumino-gfx"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []

[dependencies]
wgpu = "27.0"
thiserror = { workspace = true }
tracing = { workspace = true }
bytemuck = { version = "1.21", features = ["derive"] }
puffin = { workspace = true }
half = "2.4"
futures = { workspace = true }
anyhow = { workspace = true }
im = { version = "15.1.0", features = ["rayon"] }
rayon = "1.10"
lumino-core = { path = "../core" }
lumino-midi-loader = { path = "../midi-loader" }
