[package]
name = "lumino-gfx"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []
unstable-swappable-buffer = []

[dependencies]
wgpu = "27.0"
thiserror = { workspace = true }
tracing = { workspace = true }
bytemuck = { version = "1.21", features = ["derive"] }
puffin = { workspace = true }
half = "2.4"
