[package]
name = "lumino-core"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []
ldms-export = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.42", features = ["fs", "rt", "sync"] }
tracing = { workspace = true }
midly = { workspace = true }
rayon = "1"
bincode = "1.3.3"
zstd = { workspace = true }
encoding_rs = { workspace = true }
lumino-midi = { path = "../midi" }
lumino-dms = { path = "../dms" }
thiserror = { workspace = true }
font-kit = "0.14"
puffin = { workspace = true }

[dev-dependencies]
tokio = { version = "1.42", features = ["fs", "rt", "sync", "rt-multi-thread", "macros"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["sysinfoapi", "psapi", "processthreadsapi", "handleapi", "winnt"] }

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["sysinfoapi"] }
