[package]
name = "lumino-core"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
default = []
ldms-export = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.42", features = ["fs", "rt", "sync"] }
tracing = { workspace = true }
midly = { workspace = true }
rayon = "1"
bincode = "1.3.3"
zstd = "0.13.2"
encoding_rs = "0.8"
lumino-midi = { path = "../midi" }
lumino-dms = { path = "../dms" }
thiserror = { workspace = true }
font-kit = "0.14"
puffin = "0.19.1"

[dev-dependencies]
tokio = { version = "1.42", features = ["fs", "rt", "sync", "rt-multi-thread", "macros"] }

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["sysinfoapi"] }
