[package]
name = "lumino-memory-monitor"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["sysinfoapi", "psapi", "processthreadsapi", "handleapi", "winnt"] }

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["sysinfoapi"] }
