[package]
name = "lumino-export"
version.workspace = true
rust-version.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
lumino-dms = { path = "../dms" }
lumino-core = { path = "../core" }
lumino-midi = { path = "../midi" }
thiserror = { workspace = true }
tracing = { workspace = true }
midly = { workspace = true }
bytes = "1.9"
encoding_rs = { workspace = true }
num-bigint = { workspace = true }
tokio = { version = "1.42", features = ["fs", "rt"] }
zstd = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
# 音频导出依赖
hound = { workspace = true }
flac-encoder = { workspace = true }
xsynth-core = { git = "https://github.com/PenguinBMDevs/xsynth" }
xsynth-soundfonts = { git = "https://github.com/PenguinBMDevs/xsynth" }
rayon = "1.10"
atomic_float = "1.0"

[dev-dependencies]
tempfile = "3.0"
